update

diff --git a/radio/radio b/radio/radio
--- a/radio/radio
+++ b/radio/radio
@@ -4,6 +4,7 @@ indexurl=https://riesz.io/radio/urls.json
 indexfile=
 debug=1
 dolist=0
+station=
 
 while [ $# -gt 0 ] ; do
   arg=`echo "$1" | sed "s/^\([^=][^=]*=\)\(.*\)$/\1/g"`
@@ -18,6 +19,8 @@ while [ $# -gt 0 ] ; do
   esac
   shift
 done
+
+if [ "$station" = "" ] ; then dolist=1 ; fi
 
 if [ $debug -eq 1 ] ; then
   printf "debug     = %d\n" "$debug"
@@ -48,7 +51,15 @@ if [ $debug -eq 1 ] ; then
   printf "url  = %s\n" "$url"
 fi
 
-printf "Streaming %s\n          %s\n" "$desc" "$url"
+if [ "$url" != "" ] ; then
+  printf "Streaming %s\n          %s\n" "$desc" "$url"
 
-mpv "$url"
-echo mpv ended with code $?
+  mpv "$url"
+  echo mpv ended with code $?
+  exit $?
+else
+  echo "Couldn't find stream for station \"$station\"."
+  exit 1
+fi
+
+exit 0
